language: php

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

before_install:
  - composer install --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - vendor